### ISSUE TITLE
Sending Events only to CT

### ISSUE THREAD

**Issue by mohitagarwal** [CleverTap/clevertap-segment-android#14]
Hi is there a capability to send events to CT only and not to segment.io via `clevertap-segment-android` kit? or any workaround that you could suggest

**Comment by darshanclevertap** [comment]
@mohitagarwal If you want to send events only to CleverTap, I'd suggest you use the main [CleverTap Android SDK](https://github.com/CleverTap/clevertap-android-sdk) by following our [documentation here](https://developer.clevertap.com/docs/android-quickstart-guide)

**Comment by mohitagarwal** [comment]
Ok so will have to use Clevertap android sdk only..can't be done via Segment android sdk...cool thanks
