### ISSUE TITLE
Threadpool executor background issue.

### ISSUE THREAD

**Issue by vamshirupeek** [CleverTap/clevertap-segment-android#18]
Hi we have been facing background Threadpool executor issue. Please check the below image.

![screencapture-console-firebase-google-project-insight-38a5e-crashlytics-app-android-com-rupeek-customer-issues-f95f9b26ce36516e5d84540066d23633-2020-09-22-12_50_48](https://user-images.githubusercontent.com/45193823/93875409-8d3b9980-fcf2-11ea-8d06-d87336be344a.png)

**Comment by darshanclevertap** [comment]
Same as https://github.com/CleverTap/clevertap-android-sdk/issues/37
