### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by ajosue** [CleverTap/clevertap-segment-android#3]
Im getting this after update i try everything its look like a playservices conflict in the library or something please help.

`Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.google.android.gms.common.internal.zzi is referenced as an interface from com.google.android.gms.common.internal.zzj`

**Comment by darshanclevertap** [comment]
@ajosue Can you please share the entire stack trace? It would help us in debugging the issue better

**Comment by ajosue** [comment]
its working now with the new version 

`implementation 'com.clevertap.android:clevertap-segment-android:1.0.19'`

thank you.
