### ISSUE TITLE
cannot import com.clevertap.android.sdk.CleverTapAPI;

### ISSUE THREAD

**Issue by ajosue** [CleverTap/clevertap-segment-android#5]
hi guys since version 1.0.19 im not able to import "import com.clevertap.android.sdk.CleverTapAPI;"

so im stuck in version 1.0.18 please help me i tried using api instead of implementation and version a 1.1.0 a everything fails so i will stay in version 1.0.18

**Comment by darshanclevertap** [comment]
@ajosue Are you still facing this issue?

**Comment by ajosue** [comment]
no i fix it long time ago thank you anyway.
